config/routes.rb
Rails.application.routes.draw do
  root 'comics#index'
  get '/search_by_character', to: 'comics#search_by_character'
  post '/comics/:comic_id/favourite', to: 'comics#favourite_comic', as: 'favourite_comic'
  post '/comics/:comic_id/unfavourite', to: 'comics#unfavourite_comic', as: 'unfavourite_comic'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  serialize :favourite_comics, Hash

  scope :inactive_for_more_than, ->(period) { where('updated_at < ?', Time.current - period) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  private
  
  def set_current_user
    @user = session[:user_id].present? ? User.find(session[:user_id]) : User.create!

    session[:user_id] = @user.id
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  def index
    @comics_service = Marvel::ComicsService.new
    @comics = @comics_service.get_comics(page: comic_params[:page].to_i)
  end

  def search_by_character
    redirect_to root_path and return if comic_params[:character_name_query].blank?

    @comics_service = Marvel::ComicsService.new
    characters = @comics_service.get_characters(page: comic_params[:page].to_i, name_starts_with: comic_params[:character_name_query])
    
    @comics = characters.present? ? @comics_service.get_comics(page: comic_params[:page].to_i, character_ids: characters.map(&:id)) : []

    render :index
  end

  def favourite_comic
    @user.favourite_comics[params[:comic_id]] = true
    @user.save

    render json: { favourite_button: render_to_string('comics/_favourite_button', layout: false, locals: { user: @user, comic_id: params[:comic_id] }) }
  end

  def unfavourite_comic
    @user.favourite_comics.delete(params[:comic_id])
    @user.save

    render json: { favourite_button: render_to_string('comics/_favourite_button', layout: false, locals: { user: @user, comic_id: params[:comic_id] }) }
  end

  private 

  def comic_params
    params.permit(:page, :character_name_query, :commit)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
  def current_page
    @comics_service.current_page
  end

  def first_page?
    @comics_service.current_page == 1
  end

  def last_page?
    @comics_service.last_page == @comics_service.current_page
  end

  def user_favourite?(comic_id)
    !!@user.favourite_comics[comic_id.to_s]
  end
end

app/views/comics/_comic.html.erb
<% favourite_class = user_favourite?(comic.id) ? 'favourited' : '' %>
<div class="comic <%= favourite_class %>">
  <img class="comic-cover" src=<%= comic.thumbnail_urls[:medium] %> alt=<%= comic.title %>>
  <div class="comic-cover-overlay <%= favourite_class %>">
    <div class="favourite-button-section">
      <%= render partial: 'favourite_button', locals: { comic_id: comic.id }%>
    </div>
    <div class="comic-title">
      <p class="comic-title-text">
        <%= comic.title.upcase %>
      </p>
    </div>
  </div>
</div>

app/views/comics/_favourite_button.html.erb
<% if user_favourite?(comic_id) %>
  <%= button_to '', unfavourite_comic_path(comic_id), remote: true, class: 'unfavourite-button' %>
<% else %>
  <%= button_to '', favourite_comic_path(comic_id), remote: true, class: 'favourite-button' %>
<% end %>

app/views/comics/_page_navigation.html.erb
<% unless first_page? %>
  <%= link_to 'previous page', root_path(page: current_page - 1), class: 'page-navigation-button previous' %>
<% end %>

<% unless last_page? %>
  <%= link_to 'next page', root_path(page: current_page + 1), class: 'page-navigation-button next' %>
<% end%>

app/views/comics/index.html.erb
<div class="content">
  <% if @comics.present? %>
    <div class="comics-grid">
      <% @comics.each do |comic| %>
        <%= render partial: 'comic', locals: { comic: comic }%>
      <% end %>
    </div>

    <div class="page-navigation">
      <%= render partial: 'page_navigation' %>
    </div>
  <% else %>
    <div class="no-results">
      <p class="no-results-message">
        Aww... Seems like there are no comics matching your filters. Try searching for another character :)
      </p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComicsAppChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="logo">
        <%= link_to root_path do %>
          <%= image_tag 'marvel_logo.png' %>
        <% end %>
      </div>
      <div class="search">
        <%= form_with class: 'character-search-form', url: search_by_character_path, method: :get do |form| %>
          <%= form.text_field :character_name_query, placeholder: 'Search by Marvel character...', class: 'character-search-input', value: params[:character_name_query] %>
          <%= form.submit '', class: 'character-search-button' %>
        <% end %>
      </div>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>